name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag josephrashidmaalouf/pizzeria-bravo-food-stuff-service:$(date +%Y%m%d%H%M%S)

    # Push the Docker image
    - name: Push the Docker image
      run: docker push josephrashidmaalouf/pizzeria-bravo-food-stuff-service:$(date +%Y%m%d%H%M%S)
