name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and tag the Docker image with a timestamp
    - name: Build and tag the Docker image
      run: |
        docker build . --file Dockerfile --tag josephrashidmaalouf/pizzeria-bravo-food-stuff-service:$(date +%Y%m%d%H%M%S)
        docker tag josephrashidmaalouf/pizzeria-bravo-food-stuff-service:$(date +%Y%m%d%H%M%S) josephrashidmaalouf/pizzeria-bravo-food-stuff-service:latest

    # Push the timestamped Docker image
    - name: Push the timestamped Docker image
      run: docker push josephrashidmaalouf/pizzeria-bravo-food-stuff-service:$(date +%Y%m%d%H%M%S)

    # Push the latest tag
    - name: Push the latest Docker image
      run: docker push josephrashidmaalouf/pizzeria-bravo-food-stuff-service:latest
